---
title: "First Knit"
author: "Th3b0yn3xtd00r"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "Summer 2023"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Poway High school and Abraxas High school during my four years of secondary school. Yes, I graduated from Abraxas High School in 2018. I used to prefer Math over English but lately I've started to like both curriculums. I had trouble with English because I didn't understand it but this year has been able to show me a newfound appreciation for English so now I prefer both common core courses. I was always good at English. I just didn't enjoy it until just recently. When I write I feel as if I am able to place my thoughts down properly rather than keeping them in my brain.

## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a Windows computer that I will be using for this class. I would rate myself a 7 for my knowledge on the internet. I know the fundamentals but I still need guidance to navigate through especially for this coding Stats class.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I prefer my name to be addressed as Antonio. The name Antonio is my middle name.

## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to become an Actor, Producer, and Director, working in the entertainment industry is my goal. I have my heart set on New York University but I do not mind going to a California four year college. I am trying to get an AS-T to transfer to a four year school to obtain my BA degree.

## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




